/* cc -std=c90 -Wall -Wextra -o libwpp.so onelibwpp.c -fpic -shared */
#include "arena.c"
#include "exec.c"
#include "exec_cast.c"
#include "exec_copy.c"
#include "exec_fn.c"
#include "exec_if.c"
#include "exec_loop.c"
#include "exec_misc.c"
#include "exec_namespace.c"
#include "exec_obj.c"
#include "exec_print.c"
#include "exec_ret_stack.c"
#include "exec_scanln.c"
#include "exec_var.c"
#include "lexer.c"
#include "object.c"
